apiVersion: v1
kind: Secret
metadata:
  name: csi-driver-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: admin
  secretAccessKey: admin123456
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: http://10.0.41.95:9000
  # If not on S3, set it to ""
  region: ""
