apiVersion: v1
kind: Secret
metadata:
  name: s3fs-secret
  namespace: default
type: Opaque
stringData:
  #Access_Key_ID、Access_Key_Secret请分别使用具有指定对象存储Bucket访问权限的Access Key内容替换；
  passwd-s3fs: |-
    mqvJyofMcXSec9yR2GClQ4BLQXzH4WoX:ofro8hattenp6gm5hkax9gpjbfcqoib4
