kind: Pod
apiVersion: v1
metadata:
  name: test-s3fs-pod-1
spec:
  containers:
    - name: test-s3fs-pod-1
  image: busybox:latest
  command:
    - "/bin/sh"
  args:
    - "-c"
    - "touch /mnt/SUCCESS && sleep 60000 || exit 1"
  volumeMounts:
    - name: mntdatas3fs
      mountPath: "/mnt"
    restartPolicy: "Never"
    volumes:
      - name: mntdatas3fs
  hostPath:
    path: /mnt/data-s3fs