# 配置信息
#################### MINIO #####################
x-minio-image: &minio-image minio/minio:RELEASE.2021-07-30T00-02-00Z
x-minio-data-dir: &minio-data-dir
  # 映射文件路径
  - /mydata/minio/data:/data

#用于部署运行所依赖的基础环境组件
#sudo docker run -d -p 9000:9000 -p 9009:9009 --name minio -v /mydata/minio/data:/data -e "MINIO_ROOT_USER=admin" -e "MINIO_ROOT_PASSWORD=admin123456" --restart=always minio/minio:RELEASE.2021-07-30T00-02-00Z server /data --console-address ":9009"
#  参数含义如下：
#
#  9000数据通讯端口，比如您通过客户端或API上传对象时使用的端口
#  /data/minio为本地挂载路径
#  MINIO_ROOT_USER设置用户名
#  MINIO_ROOT_PASSWORD设置密码
#  MINIO_DOMAIN设置域名，域名的作用后面做进一步介绍
#  --console-address ":9009"为WEB访问端口

version: '3.9'
services:
  # 1.MinIO服务器
  minio:
    image: *minio-image
    container_name: minio
    ports:
      - "9000:9000"
      - "9009:9009"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: server /data --console-address ":9009"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123 #大于等于8位
    logging:
      options:
        max-size: "2048M" # 最大文件上传限制
        max-file: "10"
      driver: json-file
    volumes: *minio-data-dir
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://10.0.0.198:9000/minio/health/live"]
#      interval: 30s
#      timeout: 20s
#      retries: 3